### ISSUE TITLE
Tab Center Redux doesn't replace Tab Mix Plus

### ISSUE THREAD

**Issue by nt1m** [mozilla/extension-finder#10]
Tab Mix Plus is about configuring tab behaviour (what happens when you open a link in a new tab, etc), but that isn't really covered by Tab center redux.

**Comment by potch** [comment]
I replied in another issue, but pasting this here for future reference:

This tool is just a search interface to a set of recommendations made by the Firefox Add-ons team. There's an [ongoing discussion thread](https://discourse.mozilla.org/t/favorite-webextensions/17087/55) where people can provide feedback and suggest new alternatives.
