### ISSUE TITLE
Download Star is a better DownThemAll! alternative

### ISSUE THREAD

**Issue by nt1m** [mozilla/extension-finder#11]
It was specially created to replace DTA's mass downloads feature

**Comment by potch** [comment]
I replied in another issue, but pasting this here for future reference. Sorry for the reply-spam :)

This tool is just a search interface to a set of recommendations made by the Firefox Add-ons team. There's an [ongoing discussion thread](https://discourse.mozilla.org/t/favorite-webextensions/17087/55) where people can provide feedback and suggest new alternatives.
