### ISSUE TITLE
Crowdsource all the things!

### ISSUE THREAD

**Issue by IMSoP** [mozilla/extension-finder#12]
This is a really great idea, but a hand-picked list of 61 one-to-one mappings isn't going to do much to dispel the feeling that Firefox 57 is decimating the Add-On ecosystem. This feels like a great prototype, but if it's going to be linked in [official help pages](https://support.mozilla.org/en-US/kb/firefox-add-technology-modernizing?as=u&utm_source=inproduct) it needs to be a lot more than that.

Firstly, there should be a big prominent link for "Know of an alternative we're missing? Add it here!" It should spam a designated inbox, or be a Google Spreadsheets form, or something. Even a properly labelled link to [the "official" suggestions thread](https://discourse.mozilla.org/t/favorite-webextensions/17087) would be a start, though "register for yet another forum" isn't that encouraging.

Secondly, get rid of [the three-column spreadsheet](https://docs.google.com/spreadsheets/d/1ZzheVRDnEpAwdQ3eHDVI6Hu5om5zhp2YtSCeB0mmLUQ/edit#gid=0) and put the list in a text file in this repo. Then people can make suggestions by Pull Request too. (There's no link to this repo on the page either, I had to reverse engineer the Github URL, so add that. And a README.)

Thirdly, if you're going to hand-vet the entries, a couple of minutes glancing at each one would seem sensible. You currently have no alternative listed for FireGestures, but have [Foxy Gestures](https://addons.mozilla.org/en-GB/firefox/addon/foxy-gestures/) as an alternative to something else. The summary of that extension is "Mouse gestures for Firefox. A web extension alternative to FireGestures created by a long time FireGestures user."

Fourthly, on that note, you should be canvassing every author of a WebExtensions add-on for suggestions of legacy add-ons it could be a replacement for. Implement mozilla/addons-server#9 and you won't be in the position of having to pick a favourite.

Finally, I'm not sure why this tool even exists, since [addons.mozilla.org apparently built a feature for managing these alternatives already](https://github.com/mozilla/addons/issues/4440). That seems like a more natural home, although I've no idea if it's actually live, or if anyone ever loaded any data.

**Comment by IMSoP** [comment]
A couple of addenda:

- There are 60 items in the current list, not 61, I accidentally counted the header. I see roughly 15000 extensions on AMO listed as compatible with v56 and not v57, so that's about 0.4%
- The AMO system will be linked from the "Disabled Extensions" tab in `about:addons` (it's there in current builds if you set `extensions.legacy.enabled=false`). As I expected, it doesn't have a suggestion for FireGestures either.
- Here's yet another bit of duplicated effort: https://docs.google.com/spreadsheets/d/1TFcEXMcKrwoIAECIVyBU0GPoSmRqZ7A0VBvqeKYVSww/edit#gid=0 (Found via https://github.com/andymckay/arewewebextensionsyet.com/issues/14) This has many more suggestions than the data used here, including three for FireGestures.

**Comment by potch** [comment]
Thanks for all the leg-work checking this stuff out! Alas, this tool is just a search interface to a set of recommendations made by the Firefox Add-ons team. There's an [ongoing discussion thread](https://discourse.mozilla.org/t/favorite-webextensions/17087/55) where people can provide feedback and suggest new alternatives.

**Comment by IMSoP** [comment]
It's very disappointing that there's no will to improve this. This tool should have been one of the first things specced out when it was decided that *every single add-on* would need to be rewritten. The idea that enough people are going to sign up to some random forum and suggest exactly one alternative to every one of the *thousands* of add-ons that will suddenly stop working in people's browsers, is frankly ridiculous.

Maybe you don't feel this is your problem to solve, but you surely have a better idea of who to bang this drum in front of than me.

**Comment by IMSoP** [comment]
Hi, I realise this isn't really your problem to solve, but I had hoped to convince you the problem was real, and would be better able to find who to call out to than I am.

This really should have been one of the first projects Mozilla kicked off when they decided that every single add-on was going to need to be rewritten. It seems like it's never been treated as a priority, as shown by this tool not even being integrated with the main addons.mozilla.org site, and that makes me really worried for the future of Firefox.
