### ISSUE TITLE
Tab Center Redux is not a replacement for Tab Groups

### ISSUE THREAD

**Issue by nt1m** [mozilla/extension-finder#8]
The Tab Groups replacement is inaccurate, WE replacements exist, but Tab Center Redux is not one of them. Tab Center Redux does sidebar tabs, not tab groups.

There are some add-ons that focus on grouping though: 
https://addons.mozilla.org/en-US/firefox/addon/conex/
https://addons.mozilla.org/en-US/firefox/addon/sea-containers/
https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/?src=search

**Comment by nt1m** [comment]
Another tab groups replacement: https://addons.mozilla.org/en-US/firefox/addon/tab-workspaces/?src=search

**Comment by potch** [comment]
Hi there! Sorry about the delay in replying.

This tool is just a search interface to a set of recommendations made by the Firefox Add-ons team. There's an [ongoing discussion thread](https://discourse.mozilla.org/t/favorite-webextensions/17087/55) where people can provide feedback and suggest new alternatives.

Thanks for taking the time to find these!
