### ISSUE TITLE
Suggest multiple alternatives

### ISSUE THREAD

**Issue by nt1m** [mozilla/extension-finder#9]
A legacy add-on does not map one-to-one to a webextension alternative.

For example, Tab Mix Plus is a big add-on that covers a lot of features. Some people might need a specific feature from TMP, but not all of them.
The spreadsheet here covers multiple individual replacements for TMP features: https://docs.google.com/spreadsheets/d/1TFcEXMcKrwoIAECIVyBU0GPoSmRqZ7A0VBvqeKYVSww/edit#gid=0

Suggesting multiple alternatives will allow users to make a choice.

**Comment by potch** [comment]
I replied in another issues, but copying the meat here for future reference:

This tool is just a search interface to a set of recommendations made by the Firefox Add-ons team. There's an [ongoing discussion thread](https://discourse.mozilla.org/t/favorite-webextensions/17087/55) where people can provide feedback and suggest new alternatives.

**Comment by nt1m** [comment]
@potch I'm ok with using the discussion thread for suggesting new alternatives, but I do think the search tool shouldn't just match add-ons one-to-one with alternatives, which is what the issue is about. Not sure the discussion link is really relevant to this issue.
